# Generated by Django 3.2.12 on 2022-04-29 15:05

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('titulo', models.CharField(max_length=150, unique=True, verbose_name='Titulo del Post')),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descripcion')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('imagen_referencial', models.ImageField(max_length=255, upload_to='static/images', verbose_name='Imagen Referencial')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicacion')),
                ('autor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.categoria')),
            ],
            options={
                'ordering': ['fecha_publicacion'],
            },
        ),
    ]
