# Generated by Django 3.2.12 on 2022-03-25 13:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20220323_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen5',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
