version: '3'

volumes:
  visualizador_cc_local_postgres_data: {}
  visualizador_cc_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: visualizador_cc_local_django
    container_name: visualizador_cc_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: visualizador_cc_production_postgres
    container_name: visualizador_cc_local_postgres
    volumes:
      - visualizador_cc_local_postgres_data:/var/lib/postgresql/data:Z
      - visualizador_cc_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5434:5432"

  

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: visualizador_cc_local_mailhog
    ports:
      - "8025:8025"
