# Generated by Django 3.2.12 on 2022-04-29 15:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('cueanexo', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='CueAnexo del Establecimiento')),
                ('nom_est', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre del Establecimiento')),
                ('sector', models.CharField(blank=True, max_length=200, null=True)),
                ('ambito', models.CharField(blank=True, max_length=100, null=True)),
                ('region_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=500, null=True)),
                ('departamento', models.CharField(blank=True, max_length=500, null=True)),
                ('estado_loc', models.CharField(max_length=10, verbose_name='Estado de la localización')),
            ],
            options={
                'verbose_name_plural': 'Datos de Padron',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TablaLocalizaciones',
            fields=[
                ('cueanexo', models.OneToOneField(db_column='cueanexo', default=0, help_text='Debe coincidir con cueanexo de sistema padron', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mapa.padron', verbose_name='Cueanexo')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Localizaciones',
                'db_table': 't_localizaciones',
                'managed': True,
            },
        ),
    ]
