# Generated by Django 3.2.12 on 2022-03-22 14:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id_localizacion', models.BigIntegerField(default=0, help_text='Se debe obtener de sistema padron', primary_key=True, serialize=False, unique=True)),
                ('cueanexo', models.BigIntegerField(default=0)),
                ('nom_est', models.CharField(blank=True, max_length=250, null=True)),
                ('sector', models.CharField(blank=True, max_length=200, null=True)),
                ('ambito', models.CharField(blank=True, max_length=100, null=True)),
                ('region_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=500, null=True)),
                ('departamento', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Datos de Padron',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TablaLocalizaciones',
            fields=[
                ('datos_padron', models.OneToOneField(default=0, help_text='Se debe obtener de sistema padron', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mapa.padron')),
                ('cueanexo', models.BigIntegerField(default=0, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=5347)),
            ],
            options={
                'verbose_name_plural': 'Localizaciones',
                'db_table': 't_localizaciones',
                'managed': True,
            },
        ),
    ]
