# Generated by Django 3.2.12 on 2022-03-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_rename_datos_padron_tablalocalizaciones_id_establecimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablalocalizaciones',
            old_name='id_establecimiento',
            new_name='id_padron_est',
        ),
    ]
