# Generated by Django 3.2.12 on 2022-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_detallesescuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cueanexo', models.CharField(max_length=200)),
                ('oferta', models.CharField(max_length=200)),
                ('columna', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'planes_estudios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DetallesEscuela',
        ),
    ]
