# Generated by Django 3.2.12 on 2022-03-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_rename_id_establecimiento_tablalocalizaciones_id_padron_est'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadronOferta',
            fields=[
                ('id_oferta', models.BigIntegerField(default=0, help_text='Se debe obtener la información de Padron por ofertas', primary_key=True, serialize=False, verbose_name='Oferta')),
                ('oferta', models.CharField(default='', max_length=250, verbose_name='Oferta del establecimiento')),
            ],
        ),
        migrations.RenameField(
            model_name='tablalocalizaciones',
            old_name='id_padron_est',
            new_name='padron_est',
        ),
        migrations.RemoveField(
            model_name='tablalocalizaciones',
            name='cueanexo',
        ),
        migrations.AddField(
            model_name='padron',
            name='oferta',
            field=models.ManyToManyField(default=0, to='mapa.PadronOferta', verbose_name='Relación con Padron Ofertas'),
        ),
    ]
