# Generated by Django 3.2.12 on 2022-12-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_auto_20221212_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='padron',
            name='calle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='padron',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='padron',
            name='email_loc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='padron',
            name='numero',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='padron',
            name='ref_loc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
