# Generated by Django 3.2.12 on 2023-03-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_auto_20221220_1034'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='planestudio',
            table='mapa.v_planes_estudio',
        ),
    ]
