# Generated by Django 3.2.12 on 2022-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('', 'No es supervisor'), ('Regional 1', 'R.E. 1'), ('Sub-Regional 1A', 'SUB. R.E. 1-A'), ('Regional 2', 'R.E. 2'), ('Sub-Regional 2', 'SUB. R.E. 2'), ('Regional 3', 'R.E. 3'), ('Sub-Regional 3', 'SUB. R.E. 3'), ('Regional 4A', 'R.E. 4-A'), ('Regional 4B', 'R.E. 4-B'), ('Regional 5', 'R.E. 5'), ('Sub-Regional 5', 'SUB. R.E. 5'), ('Regional 6', 'R.E. 6'), ('Regional 7', 'R.E. 7'), ('Regional 8A', 'R.E. 8-A'), ('Regional 8B', 'R.E. 8-B'), ('Regional 9', 'R.E. 9'), ('Regional 10A', 'R.E. 10-A'), ('Regional 10B', 'R.E. 10-B'), ('Regional 10C', 'R.E. 10-C'), ('Sub-Regional 1B', 'SUB. R.E. 1-B')], default=None, help_text='Seleccione la regional del supervisor', max_length=20, null=True, verbose_name='Regional Educativa'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.BooleanField(default=False, help_text='Marque si es supervisor', verbose_name='¿Es supervisor?'),
        ),
    ]
