log:
  level: INFO

entryPoints:
  web:
    address: ":80"

http:
  routers:
    django-router:
      rule: "Host(`visoreducativochaco.com.ar`)"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

